# Generated by Django 4.2.6 on 2023-12-18 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "intensity",
                    models.CharField(
                        blank=True,
                        choices=[
                            (None, "No Intensity"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("very high", "Very High"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Intensity",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "advantages",
                    models.TextField(blank=True, null=True, verbose_name="Advantages"),
                ),
                (
                    "disadvantages",
                    models.TextField(
                        blank=True, null=True, verbose_name="Disadvantages"
                    ),
                ),
                (
                    "emotion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sad", "Sad"),
                            ("happy", "Happy"),
                            ("worry", "Worry"),
                            ("angry", "Angry"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Emotion",
                    ),
                ),
                (
                    "emotion_intensity",
                    models.CharField(
                        blank=True,
                        choices=[
                            (None, "No Intensity"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("very high", "Very High"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Emotion Intensity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Facilitator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(verbose_name="Description")),
            ],
        ),
        migrations.CreateModel(
            name="Thought",
            fields=[
                (
                    "action_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.action",
                    ),
                ),
            ],
            bases=("core.action",),
        ),
        migrations.CreateModel(
            name="ActionDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateField(auto_now_add=True, null=True)),
                ("hour", models.PositiveSmallIntegerField(null=True)),
                ("minute", models.PositiveSmallIntegerField(null=True)),
                ("second", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "duration_total",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "action",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.action",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="action",
            name="facilitator",
            field=models.ManyToManyField(blank=True, to="core.facilitator"),
        ),
        migrations.AddField(
            model_name="action",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="ThoughtDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "hour",
                    models.PositiveSmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "minute",
                    models.PositiveSmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "second",
                    models.PositiveSmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "duration_total",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "thought",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.thought",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="action",
            name="thought_facilitator",
            field=models.ManyToManyField(blank=True, to="core.thought"),
        ),
    ]
