# Generated by Django 4.2.6 on 2024-03-30 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(verbose_name='Description')),
                ('advantages', models.TextField(blank=True, null=True, verbose_name='Advantages')),
                ('disadvantages', models.TextField(blank=True, null=True, verbose_name='Disadvantages')),
                ('action_facilitator', models.ManyToManyField(blank=True, related_name='facilitator_action', to='core.action')),
            ],
        ),
        migrations.CreateModel(
            name='Thought',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.action')),
            ],
            bases=('core.action',),
        ),
        migrations.CreateModel(
            name='Facilitator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(verbose_name='Description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(verbose_name='Description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActionDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('emotion', models.CharField(blank=True, choices=[('sad', 'Sad'), ('happy', 'Happy'), ('worry', 'Worry'), ('angry', 'Angry')], max_length=20, null=True, verbose_name='Emotion')),
                ('emotion_intensity', models.CharField(blank=True, choices=[(None, 'No Intensity'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very high', 'Very High')], max_length=20, null=True, verbose_name='Emotion Intensity')),
                ('hour', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('minute', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('second', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('duration_total', models.PositiveBigIntegerField(blank=True, null=True)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.action')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='environment_facilitator',
            field=models.ManyToManyField(blank=True, related_name='facilitator_environment', to='core.environment'),
        ),
        migrations.AddField(
            model_name='action',
            name='facilitator',
            field=models.ManyToManyField(blank=True, to='core.facilitator'),
        ),
        migrations.AddField(
            model_name='action',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ThoughtDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('emotion', models.CharField(blank=True, choices=[('sad', 'Sad'), ('happy', 'Happy'), ('worry', 'Worry'), ('angry', 'Angry')], max_length=20, null=True, verbose_name='Emotion')),
                ('emotion_intensity', models.CharField(blank=True, choices=[(None, 'No Intensity'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very high', 'Very High')], max_length=20, null=True, verbose_name='Emotion Intensity')),
                ('hour', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('minute', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('second', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('duration_total', models.PositiveBigIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('thought', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.thought')),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='thought_facilitator',
            field=models.ManyToManyField(blank=True, related_name='facilitator_thought', to='core.thought'),
        ),
    ]
