# Generated by Django 5.2 on 2026-02-10 20:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_voiceactionentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VoiceActionEntry',
            new_name='ActionRaw',
        ),
        migrations.RenameModel(
            old_name='VoiceThoughtEntry',
            new_name='ThoughtRaw',
        ),
        migrations.AlterModelOptions(
            name='actionraw',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Action Raw', 'verbose_name_plural': 'Actions Raw'},
        ),
        migrations.AlterModelOptions(
            name='thoughtraw',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Thought Raw', 'verbose_name_plural': 'Thoughts Raw'},
        ),
    ]
