# Generated by Django 4.2.6 on 2024-01-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_thoughtdate_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="actiondate",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="actiondate",
            name="timestamp",
            field=models.DateField(blank=True, null=True),
        ),
    ]
