# Generated by Django 4.2.6 on 2024-01-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_actiondate_time_alter_actiondate_timestamp"),
    ]

    operations = [
        migrations.RenameField(
            model_name="actiondate",
            old_name="timestamp",
            new_name="date",
        ),
        migrations.AddField(
            model_name="actiondate",
            name="date_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
