# Generated by Django 4.2.6 on 2024-01-21 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0006_rename_timestamp_actiondate_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="actiondate",
            name="emotion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sad", "Sad"),
                    ("happy", "Happy"),
                    ("worry", "Worry"),
                    ("angry", "Angry"),
                ],
                max_length=20,
                null=True,
                verbose_name="Emotion",
            ),
        ),
        migrations.AddField(
            model_name="actiondate",
            name="emotion_intensity",
            field=models.CharField(
                blank=True,
                choices=[
                    (None, "No Intensity"),
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("very high", "Very High"),
                ],
                max_length=20,
                null=True,
                verbose_name="Emotion Intensity",
            ),
        ),
        migrations.AddField(
            model_name="actiondate",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="actiondate",
            name="hour",
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="actiondate",
            name="minute",
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="actiondate",
            name="second",
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
