# Generated by Django 4.2.6 on 2024-03-13 12:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_environment_action_environment_facilitator"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="actiondate",
            name="emotion",
        ),
        migrations.RemoveField(
            model_name="actiondate",
            name="emotion_intensity",
        ),
    ]
