# Generated by Django 4.2.6 on 2024-03-17 13:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_actiondate_emotion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='emotion',
        ),
        migrations.RemoveField(
            model_name='action',
            name='emotion_intensity',
        ),
        migrations.RemoveField(
            model_name='action',
            name='intensity',
        ),
        migrations.AddField(
            model_name='actiondate',
            name='emotion',
            field=models.CharField(blank=True, choices=[('sad', 'Sad'), ('happy', 'Happy'), ('worry', 'Worry'), ('angry', 'Angry')], max_length=20, null=True, verbose_name='Emotion'),
        ),
        migrations.AddField(
            model_name='actiondate',
            name='emotion_intensity',
            field=models.CharField(blank=True, choices=[(None, 'No Intensity'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very high', 'Very High')], max_length=20, null=True, verbose_name='Emotion Intensity'),
        ),
        migrations.AlterField(
            model_name='facilitator',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
