# Generated by Django 4.2.6 on 2023-12-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="action_facilitator",
            field=models.ManyToManyField(
                blank=True, related_name="facilitator_action", to="core.action"
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="thought_facilitator",
            field=models.ManyToManyField(
                blank=True, related_name="facilitator_thought", to="core.thought"
            ),
        ),
    ]
