# Generated by Django 4.2.6 on 2023-11-01 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='State',
            new_name='ThoughtDate',
        ),
    ]
