# Generated by Django 4.2.6 on 2024-01-06 23:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_action_action_facilitator_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="thoughtdate",
            name="emotion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sad", "Sad"),
                    ("happy", "Happy"),
                    ("worry", "Worry"),
                    ("angry", "Angry"),
                ],
                max_length=20,
                null=True,
                verbose_name="Emotion",
            ),
        ),
        migrations.AddField(
            model_name="thoughtdate",
            name="emotion_intensity",
            field=models.CharField(
                blank=True,
                choices=[
                    (None, "No Intensity"),
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("very high", "Very High"),
                ],
                max_length=20,
                null=True,
                verbose_name="Emotion Intensity",
            ),
        ),
    ]
