# Generated by Django 4.2.6 on 2023-11-01 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_thoughtdate_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thoughtdate',
            old_name='date',
            new_name='timestamp',
        ),
    ]
