# Generated by Django 4.2.6 on 2023-11-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_date_thoughtdate_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thoughtdate',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
