# Generated by Django 4.2.6 on 2023-11-06 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_thoughtdate_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='thought',
            name='emotion',
            field=models.CharField(blank=True, choices=[('sad', 'Sad'), ('happy', 'Happy'), ('worry', 'Worry'), ('angry', 'Angry')], max_length=20, null=True),
        ),
    ]
