# Generated by Django 4.2.6 on 2023-11-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_thought_emotion"),
    ]

    operations = [
        migrations.AddField(
            model_name="thought",
            name="emotion_intensity",
            field=models.CharField(
                blank=True,
                choices=[
                    (None, "No Intensity"),
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("severe", "severe"),
                ],
                max_length=20,
                null=True,
                verbose_name="emotion intensitY",
            ),
        ),
        migrations.AddField(
            model_name="thought",
            name="intensity",
            field=models.CharField(
                blank=True,
                choices=[
                    (None, "No Intensity"),
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("severe", "Severe"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
