# Generated by Django 4.2.6 on 2023-11-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_thought_emotion_intensity_thought_intensity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="thought",
            name="intensity",
        ),
        migrations.AddField(
            model_name="thought",
            name="thought_intensity",
            field=models.CharField(
                blank=True,
                choices=[
                    (None, "No Intensity"),
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("severe", "Severe"),
                ],
                max_length=20,
                null=True,
                verbose_name="Thought Intensity",
            ),
        ),
        migrations.AlterField(
            model_name="thought",
            name="emotion_intensity",
            field=models.CharField(
                blank=True,
                choices=[
                    (None, "No Intensity"),
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("severe", "severe"),
                ],
                max_length=20,
                null=True,
                verbose_name="Emotion Intensity",
            ),
        ),
    ]
