# Generated by Django 4.2.6 on 2023-11-11 01:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_remove_thought_intensity_thought_thought_intensity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thought",
            name="advantages",
            field=models.TextField(blank=True, null=True, verbose_name="Advantages"),
        ),
        migrations.AlterField(
            model_name="thought",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="thought",
            name="disadvantages",
            field=models.TextField(blank=True, null=True, verbose_name="Disadvantages"),
        ),
        migrations.AlterField(
            model_name="thought",
            name="emotion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sad", "Sad"),
                    ("happy", "Happy"),
                    ("worry", "Worry"),
                    ("angry", "Angry"),
                ],
                max_length=20,
                null=True,
                verbose_name="Emotion",
            ),
        ),
    ]
