# Generated by Django 4.2.6 on 2023-11-24 03:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_thought_emotion_intensity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Facilitator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(verbose_name="Description")),
            ],
        ),
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "advantages",
                    models.TextField(blank=True, null=True, verbose_name="Advantages"),
                ),
                (
                    "disadvantages",
                    models.TextField(
                        blank=True, null=True, verbose_name="Disadvantages"
                    ),
                ),
                (
                    "emotion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sad", "Sad"),
                            ("happy", "Happy"),
                            ("worry", "Worry"),
                            ("angry", "Angry"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Emotion",
                    ),
                ),
                (
                    "emotion_intensity",
                    models.CharField(
                        blank=True,
                        choices=[
                            (None, "No Intensity"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("severe", "Severe"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Emotion Intensity",
                    ),
                ),
                (
                    "facilitator",
                    models.ManyToManyField(blank=True, to="core.facilitator"),
                ),
            ],
        ),
    ]
