# Generated by Django 4.2.6 on 2023-11-24 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_facilitator_action"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("duration", models.PositiveSmallIntegerField()),
                (
                    "action",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.action",
                    ),
                ),
            ],
        ),
    ]
