# Generated by Django 4.2.6 on 2023-11-24 03:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_actiondate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actiondate",
            name="duration",
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name="actiondate",
            name="timestamp",
            field=models.DateField(),
        ),
    ]
