# Generated by Django 4.2.6 on 2023-11-24 05:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_alter_actiondate_duration_alter_actiondate_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="actiondate",
            name="hour",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="actiondate",
            name="minute",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="actiondate",
            name="second",
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
