# Generated by Django 4.2.6 on 2023-11-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_actiondate_hour_actiondate_minute_actiondate_second"),
    ]

    operations = [
        migrations.AddField(
            model_name="actiondate",
            name="duration_total",
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
