# Generated by Django 4.2.6 on 2023-11-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_actiondate_duration_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actiondate",
            name="duration_total",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="actiondate",
            name="second",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
