# Generated by Django 4.2.6 on 2023-11-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_alter_actiondate_duration_total_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="actiondate",
            name="duration",
        ),
        migrations.AddField(
            model_name="action",
            name="thought_facilitator",
            field=models.ManyToManyField(blank=True, to="core.thought"),
        ),
    ]
