# Generated by Django 4.2.6 on 2023-12-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_remove_actiondate_duration_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="thoughtdate",
            name="duration",
        ),
        migrations.AddField(
            model_name="thoughtdate",
            name="duration_total",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="thoughtdate",
            name="hour",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="thoughtdate",
            name="minute",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="thoughtdate",
            name="second",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
