# Generated by Django 4.2.6 on 2023-12-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_remove_thoughtdate_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thoughtdate",
            name="hour",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="thoughtdate",
            name="minute",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
