# Generated by Django 4.2.6 on 2023-12-05 02:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_alter_thoughtdate_hour_alter_thoughtdate_minute"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thoughtdate",
            name="hour",
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="thoughtdate",
            name="minute",
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="thoughtdate",
            name="second",
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
